# scripts/set_env.ps1
# Create or overwrite Server/.env for PatientConnect360 (Windows PowerShell)
# Usage from repo root: .\scripts\set_env.ps1

[CmdletBinding()]
param()

function Generate-JwtSecret {
    $bytes = New-Object byte[] 48
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return ([System.BitConverter]::ToString($bytes) -replace '-', '').ToLower()
}

function Read-OrDefault {
    param(
        [Parameter(Mandatory = $true)][string]$Prompt,
        [Parameter(Mandatory = $true)][string]$Default
    )
    $value = Read-Host "$Prompt [$Default]"
    if ([string]::IsNullOrWhiteSpace($value)) { return $Default }
    return $value
}

# Resolve repo root from script location so this works regardless of current shell path.
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$envDir = Join-Path -Path $repoRoot -ChildPath "Server"
$envPath = Join-Path $envDir ".env"

if (-not (Test-Path $envDir)) {
    throw "Could not find Server directory at: $envDir"
}

Write-Host ""
Write-Host "This will create or overwrite: $envPath"
Write-Host "Core runtime needs: DATABASE_URL + JWT_SECRET (+ ADMIN_* for seeded admin flow)."
Write-Host "Twilio/SendGrid/SMTP values are optional and can be left blank for local setup."
Write-Host ""

$defaultDb = "postgresql://<username>:<password>@pc360-db-2026.postgres.database.azure.com:5432/<database>?schema=public&sslmode=require"
$db = Read-OrDefault -Prompt "DATABASE_URL" -Default $defaultDb
$port = Read-OrDefault -Prompt "PORT" -Default "4000"
$nodeEnv = Read-OrDefault -Prompt "NODE_ENV" -Default "development"

$useGen = Read-Host "Generate a strong JWT_SECRET automatically? (Y/n)"
if ([string]::IsNullOrWhiteSpace($useGen) -or $useGen -match "^[Yy]") {
    $jwt = Generate-JwtSecret
    Write-Host "Generated JWT_SECRET (hex, 48 bytes)."
} else {
    $jwt = Read-Host "JWT_SECRET"
}

$twilioAccountSid = Read-Host "TWILIO_ACCOUNT_SID (optional, must start with AC if provided)"
$twilioAuthToken = Read-Host "TWILIO_AUTH_TOKEN (optional)"
$twilioVerifyServiceSid = Read-Host "TWILIO_VERIFY_SERVICE_SID (optional, starts with VA)"

$sendgridApiKey = Read-Host "SENDGRID_API_KEY (optional, legacy)"
$smtpFromEmail = Read-Host "SMTP_FROM_EMAIL (optional, legacy)"
$smtpFromName = Read-OrDefault -Prompt "SMTP_FROM_NAME (legacy)" -Default "MediHealth"
$cookieName = Read-OrDefault -Prompt "COOKIE_NAME (legacy)" -Default "auth"

$adminEmail = Read-OrDefault -Prompt "ADMIN_EMAIL" -Default "admin@example.com"
$adminUser = Read-OrDefault -Prompt "ADMIN_USERNAME" -Default "admin"

Write-Host "ADMIN_PASSWORD (input hidden, press Enter to use default AdminPass!2026):"
$securePwd = Read-Host -AsSecureString
$adminPassword = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($securePwd)
)
if ([string]::IsNullOrWhiteSpace($adminPassword)) {
    $adminPassword = "AdminPass!2026"
    Write-Host "No password entered - using default. Change this immediately in shared environments."
}

$adminOverwrite = Read-OrDefault -Prompt "ADMIN_OVERWRITE (true/false)" -Default "false"
$adminDisplay = Read-OrDefault -Prompt "ADMIN_DISPLAY_NAME" -Default "Platform Admin"
$adminPhone = Read-Host "ADMIN_PHONE (optional)"
$adminSuper = Read-OrDefault -Prompt "ADMIN_SUPER (true/false)" -Default "true"

$envContent = @"
# Server environment configuration for PatientConnect360
# Generated by scripts/set_env.ps1
DATABASE_URL="$db"
PORT=$port
NODE_ENV="$nodeEnv"
JWT_SECRET="$jwt"
TWILIO_ACCOUNT_SID="$twilioAccountSid"
TWILIO_AUTH_TOKEN="$twilioAuthToken"
TWILIO_VERIFY_SERVICE_SID="$twilioVerifyServiceSid"
SENDGRID_API_KEY="$sendgridApiKey"
SMTP_FROM_EMAIL="$smtpFromEmail"
SMTP_FROM_NAME="$smtpFromName"
COOKIE_NAME="$cookieName"
ADMIN_EMAIL="$adminEmail"
ADMIN_USERNAME="$adminUser"
ADMIN_PASSWORD="$adminPassword"
ADMIN_OVERWRITE="$adminOverwrite"
ADMIN_DISPLAY_NAME="$adminDisplay"
ADMIN_PHONE="$adminPhone"
ADMIN_SUPER="$adminSuper"
"@

# Write UTF-8 to avoid encoding issues.
Set-Content -Path $envPath -Value $envContent -Encoding utf8 -Force

# Restrict file permissions to current user.
try {
    $username = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
    icacls $envPath /inheritance:r | Out-Null
    icacls $envPath /grant:r "${username}:(F)" | Out-Null
    icacls $envPath /remove:g "Everyone" | Out-Null
    icacls $envPath /remove:g "Users" | Out-Null
    Write-Host ""
    Write-Host "Created $envPath and applied restrictive ACLs for user $username."
} catch {
    Write-Warning "Created .env but failed to fully set ACLs via icacls. Restrict file permissions manually."
}

Write-Host "Done. App can run without Twilio/SendGrid/SMTP values, but OTP/email-related routes will be unavailable until configured."
Write-Host "Do not commit Server/.env to source control."
