#!/usr/bin/env bash
# Create or overwrite Server/.env for PatientConnect360 (macOS/Linux)
# Usage from repo root: ./scripts/set_env.sh

set -euo pipefail

generate_jwt_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 48
  else
    # Fallback if openssl is unavailable
    head -c 48 /dev/urandom | xxd -p -c 256
  fi
}

read_or_default() {
  local prompt="$1"
  local default_value="$2"
  local value
  read -r -p "$prompt [$default_value]: " value
  if [[ -z "${value// }" ]]; then
    echo "$default_value"
  else
    echo "$value"
  fi
}

# Resolve repo root relative to this script location.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_DIR="$REPO_ROOT/Server"
ENV_PATH="$ENV_DIR/.env"

if [[ ! -d "$ENV_DIR" ]]; then
  echo "Could not find Server directory at: $ENV_DIR"
  exit 1
fi

echo
echo "This will create or overwrite: $ENV_PATH"
echo "Core runtime needs: DATABASE_URL + JWT_SECRET (+ ADMIN_* for seeded admin flow)."
echo "Twilio/SendGrid/SMTP values are optional and can be left blank for local setup."
echo

DEFAULT_DB='postgresql://<username>:<password>@pc360-db-2026.postgres.database.azure.com:5432/<database>?schema=public&sslmode=require'
DATABASE_URL="$(read_or_default "DATABASE_URL" "$DEFAULT_DB")"
PORT="$(read_or_default "PORT" "4000")"
NODE_ENV="$(read_or_default "NODE_ENV" "development")"

read -r -p "Generate a strong JWT_SECRET automatically? (Y/n): " USE_GEN
if [[ -z "${USE_GEN:-}" || "$USE_GEN" =~ ^[Yy]$ ]]; then
  JWT_SECRET="$(generate_jwt_secret)"
  echo "Generated JWT_SECRET (hex, 48 bytes)."
else
  read -r -p "JWT_SECRET: " JWT_SECRET
fi

read -r -p "TWILIO_ACCOUNT_SID (optional, must start with AC if provided): " TWILIO_ACCOUNT_SID
read -r -p "TWILIO_AUTH_TOKEN (optional): " TWILIO_AUTH_TOKEN
read -r -p "TWILIO_VERIFY_SERVICE_SID (optional, starts with VA): " TWILIO_VERIFY_SERVICE_SID

read -r -p "SENDGRID_API_KEY (optional, legacy): " SENDGRID_API_KEY
read -r -p "SMTP_FROM_EMAIL (optional, legacy): " SMTP_FROM_EMAIL
SMTP_FROM_NAME="$(read_or_default "SMTP_FROM_NAME (legacy)" "MediHealth")"
COOKIE_NAME="$(read_or_default "COOKIE_NAME (legacy)" "auth")"

ADMIN_EMAIL="$(read_or_default "ADMIN_EMAIL" "admin@example.com")"
ADMIN_USERNAME="$(read_or_default "ADMIN_USERNAME" "admin")"

echo "ADMIN_PASSWORD (input hidden, press Enter to use default AdminPass!2026):"
read -r -s ADMIN_PASSWORD
echo
if [[ -z "${ADMIN_PASSWORD// }" ]]; then
  ADMIN_PASSWORD="AdminPass!2026"
  echo "No password entered - using default. Change this immediately in shared environments."
fi

ADMIN_OVERWRITE="$(read_or_default "ADMIN_OVERWRITE (true/false)" "false")"
ADMIN_DISPLAY_NAME="$(read_or_default "ADMIN_DISPLAY_NAME" "Platform Admin")"
read -r -p "ADMIN_PHONE (optional): " ADMIN_PHONE
ADMIN_SUPER="$(read_or_default "ADMIN_SUPER (true/false)" "true")"

cat > "$ENV_PATH" <<EOF
# Server environment configuration for PatientConnect360
# Generated by scripts/set_env.sh
DATABASE_URL="$DATABASE_URL"
PORT=$PORT
NODE_ENV="$NODE_ENV"
JWT_SECRET="$JWT_SECRET"
TWILIO_ACCOUNT_SID="$TWILIO_ACCOUNT_SID"
TWILIO_AUTH_TOKEN="$TWILIO_AUTH_TOKEN"
TWILIO_VERIFY_SERVICE_SID="$TWILIO_VERIFY_SERVICE_SID"
SENDGRID_API_KEY="$SENDGRID_API_KEY"
SMTP_FROM_EMAIL="$SMTP_FROM_EMAIL"
SMTP_FROM_NAME="$SMTP_FROM_NAME"
COOKIE_NAME="$COOKIE_NAME"
ADMIN_EMAIL="$ADMIN_EMAIL"
ADMIN_USERNAME="$ADMIN_USERNAME"
ADMIN_PASSWORD="$ADMIN_PASSWORD"
ADMIN_OVERWRITE="$ADMIN_OVERWRITE"
ADMIN_DISPLAY_NAME="$ADMIN_DISPLAY_NAME"
ADMIN_PHONE="$ADMIN_PHONE"
ADMIN_SUPER="$ADMIN_SUPER"
EOF

# Restrict .env permissions to current user
chmod 600 "$ENV_PATH"

echo
echo "Created $ENV_PATH and set permissions to 600."
echo "Done. App can run without Twilio/SendGrid/SMTP values, but OTP/email-related routes will be unavailable until configured."
echo "Do not commit Server/.env to source control."
